### ISSUE TITLE
A couple questions about Host Applications

### ISSUE THREAD

**Issue by carl-cimon** [eclipse-sparkplug/sparkplug#249]
I'm working on an project that will be using sparkplug to transmit PLC data from our back end application(s) to the front end application(s). Our goal is to build a communication system such that we could have a defined number of Edge Nodes but 0 to N number of Host Applications, and ideally this number can be scalable during runtime. The data flow using the pub/sub system of MQTT/sparkplug is perfect for us, but we haven't figured out where the Primary Application fits in our use case yet, so I have a couple questions:

1) Is a Primary Host Application required?
    - In the case that we only supply one broker, and thus do not need the Primary Host Application to facilitate the active server, it seems unnecessary to need to designate one of the Host Applications as the Primary Application.
    - And if it is required, would we be able to dynamically assign it during runtime, using something like a "Node Control/Register Primary Application" metric to promote already connected Host Applications? Hot-swapping Primary Applications was mentioned, but  I imagine that this is a slightly different case.
2) Does the Edge Node need to know the ID of all Host Applications before starting?
    - Ideally we would be able to dynamically assign IDs to the Host Application(s) as we turn them online, as we may not know how many will be used.
    - We would be able to guarantee that the IDs are unique, and could follow a pattern like "Host-App-[number]" so that the Edge Nodes would have some for of filter if necessary.
3) Are Edge Nodes allowed to be connected to different brokers, as long as the Primary Application is ONLINE on both?
    - Based on my current understanding, this could occur if Edge Node 1 can connect to the first broker, but Edge Node 2 cannot and thus connects to the second broker, with the Primary Application having an ONLINE state on both.
4) Are we allowed to have multiple Primary Applications?
    - In section 3 of the development spec it states "Sparkplug does support the notion of multiple Primary Host Applications for any one Edge Node", however I'm not sure how that would work for multiple brokers, as there could be cases where not all Primary Applications are able to connect to the same broker.

Apologies if this is not the correct place to ask these questions, or if I missed the answers to any of them in the spec. Thanks for your hard work, the most recent version of the development spec clears up most of vague parts within the 2.2 version.

**Comment by bryce-nakatani** [comment]
These are great questions and thanks for bringing these up. Thank you for
your interest!

> 1. Is a Primary Host Application required?
A Primary Host App is not required.

However, this is the only technique that allows the edge nodes to know the
primary host's state of connection to the broker.

If you don't implement Primary Host, your edge nodes could be publishing to
a broker without a host listening.

If you should implement a historical option, then Primary Host Application
is more significant. The historical option itself allows the edge node to
store data updates should the edge lose connection to the broker or the
Primary Host is offline.

The Primary Host implementation allows edge nodes to know when to begin
accumulating data (when the host is offline) and when to publish both live
and historical data (when the host is online).

Though keep an eye on the upcoming 3.0 Sparkplug specification. The MQTT
Topic and the Primary Host Application payload is being reviewed.

Note. When implementing Primary Host in the edge node, you may want to
employ some kind of random delay to defer when your edge node begins
issuing its birth certificates and subsequent data. If your
application scales to 'n' and 'n' is quite a large number, imagine what
happens when all 'n' edge nodes synchronously receive the publication to go
online. The broker, the host application, and possibly the network may get
pretty swamped. You may want a "random span" a user may set (with a minimum
default) to spread out what could be a sudden traffic jam of publications.

> 2. Does the Edge Node need to know the ID of all Host Applications before
starting?
The Primary Host ID is (in the 2.x specification) is the MQTT topic the
Primary Host publishes its STATE.

The edge nodes need to be configured with this parameter.

> 3. Are Edge Nodes allowed to be connected to different brokers?
The edge node must only be connected to a single broker at any time.

> 4. Are we allowed to have multiple Primary Applications?
Currently there are no provisions for an edge node to handle multiple
Primary Applications.

This is something I personally would like to see added in a future
specification.

When the edge node receives an OFFLINE primary application state, the edge
node should disconnect the OFFLINE broker and connect to the next broker.
The edge node should wait for an ONLINE state (or possibly no state may be
published). If the edge node does not receive the ONLINE indication, the
edge node should repeat the disconnect/connect sequence described.

Even with the 3.0 specification modifications, the Primary Host topic and
payload may change but the algorithm will likely remain the same.

The 3.0 specification's release is coming up very soon too.

**Comment by bryce-nakatani** [comment]
Good observation in your multiple primary host/edge node scenario. That
situation can occur.

Off the top of my head, there are a couple ways you can force the use of a
specific broker.

1. You mentioned the use of the "Node Control/Next Server" (as a host
application driven NCMD). This informs the edge node to move onto the next
server in its list (and that test for STATE algorithm I mentioned earlier
applies).
2. I suppose you could also employ logic in the host to drive the primary
host state to force edge nodes. Though if you have a large scale quantity
of nodes, this process could be a little brutal whereas #1 can be performed
more conveniently and at a manageable rate.

You don't want non-primary host applications to publish a STATE message,
especially if your primary host is a data historian. Other (non-primary)
host applications publishing a STATE will spoof the edge nodes into syncing
to the wrong host.

**Comment by bryce-nakatani** [comment]
Closed.
