### ISSUE TITLE
MQTT Broker : Sparkplug Aware Test 

### ISSUE THREAD

**Issue by Mahersrasra** [eclipse-sparkplug/sparkplug#473]
### What do you want to know?

Hello everyone, I'm currently in the process of confirming whether my MQTT broker aligns with Sparkplug compliance. I'm encountering some uncertainty surrounding the Sparkplug awareness test. 
I'm unsure whether I should establish a connection to the HIVEMQ broker or utilize my own broker. 
I proceeded by connecting the Edge Node to my personal MQTT broker and observed the subsequent outcome. Could someone clarify the specifics of the test case and provide an explanation for the obtained results?

![image](https://github.com/eclipse-sparkplug/sparkplug/assets/78274224/a543c181-1588-4964-9f65-ebcfdc2c2cdb)

Test results with when connecting with my own broker 

![image](https://github.com/eclipse-sparkplug/sparkplug/assets/78274224/e4579dbf-4965-4d4f-888c-a9c32b015022)

### Version

3.0.0 (Default)

### Accept EFTL Terms

- [X] I agree to the terms of EFTL

**Comment by bryce-nakatani** [comment]
Thank you for reaching out.

The "NOT EXECUTED" states means that the test criteria were not evaluated.
These are associated with the optional "Sparkplug Aware MQTT Server".

To find information about the Sparkplug Aware MQTT Server, take a look at
section 10.1.4 in the specification
<https://www.eclipse.org/tahu/spec/sparkplug_spec.pdf>.

If you would like to find out more about specific test criteria, search the
specification for the criteria tag. For example, if you searched for
"conformance-mqtt-aware-store", you'll find a tag in the specification that
looks like "tck-id-conformance-mqtt-aware-store".

**Comment by Mahersrasra** [comment]
Thank you for your quick reply. I want to understand the potential implications of these test results on the acceptance of the conformance appliance. Could you clarify whether it's obligatory to successfully pass these tests for the appliance's approval?
I'm particularly interested in comprehending the significance of the result labeled as "not executed" in the test outcomes.

**Comment by bryce-nakatani** [comment]
The Sparkplug Aware MQTT Server functionality is optional.

In a nutshell, the functionality retains birth certificates and defines a
topic structure on how to subscribe to them for retrieval.

Since the feature is optional, MQTT servers that don't implement this
option may still gain Sparkplug acceptance as long as the server passes the
other required (must) criteria.

Admittedly, the test results can be a little overwhelming/confusing. The
not executed status was to separate what was initially a boolean pass/fail.
Since the specification has optional sections, they initially showed up as
"fail." A third test state (not executed) was added to help clarify this
situation.

My experience with the TCK (from the edge node perspective) is that if a
"must" criteria fails, the TCK immediately terminates.

If you would like to see an implementation of a Sparkplug Aware add-on and
evaluate it, here is a link
<https://github.com/hivemq/hivemq-sparkplug-aware-extension/tree/master> to
a HiveMQ Community extension.

**Comment by Mahersrasra** [comment]
Okay thank you for being responsive
